//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignupWithLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }
        [DisplayName("First Name")]
        [Required(ErrorMessage ="First name is required")]
        
        public string firstname { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Last name is required")]
        public string lastname { get; set; }
        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is required")]
        public string gender { get; set; }
        [DisplayName("Age")]
        [Required(ErrorMessage = "Age is required")]
        public int age { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is required")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage ="Invalid email")]
        public string email { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "User name is required")]
       
        public string username { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password  is required")]
        public string password { get; set; }
        [DisplayName("Confirm Password")]
        
        [Compare("password",ErrorMessage ="Password is not identical")]
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string confirmpassword { get; set; }
    }
}
